{
 "title": "Monitoring Microservices in Docker",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Metrics (in %)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"monitoring_svc.*\"}[30s])) by (name) / sum(container_spec_cpu_quota{name=~\"monitoring_svc.*\"} / container_spec_cpu_period{name =~\"monitoring_svc.*\"}) by (name) * 100"
    }
   ]
  },
  {
   "title": "Memory Metrics (in MB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"monitoring_svc.*\"} / 1024 / 1024) by (name)"
    }
   ]
  },
  {
   "title": "Total CPU Usage (in %)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"monitoring_svc.*\"}[30s])) / sum(container_spec_cpu_quota{name=~\"monitoring_svc.*\"} / container_spec_cpu_period{name=~\"monitoring_svc.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Memory Usage (in MB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"monitoring_svc.*\"} / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "Math HTTP Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=\"math\"}[30s])) by (code)"
    }
   ]
  },
  {
   "title": "Greeter HTTP Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=\"greeter\"}[30s])) by (code)"
    }
   ]
  },
  {
   "title": "Total Throughput (in req/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=\"math\"}[30s])) + sum(rate(haproxy_backend_http_responses_total{backend=\"greeter\"}[30s]))"
    }
   ]
  }
 ]
}